### PR TITLE
Fixed wrong statusCode

### PR DESCRIPTION
**Pull request by so1ve**
During my use, I found that if I use this middleware as a routing middleware and throw an error while processing the routing logic, the returned status code will be wrong.

### CODE REVIEW

**Comment by halvardssm** [comment]
@so1ve Interesting! Good that you found this issue! I'd merge it immediately, however, there are a couple of other unrelated changes in your PR. Could you create a new PR with only the middleware changes? 😃

**Comment by so1ve** [comment]
BTW, I think the AlgorithmInput section in the README needs to be changed

**Comment by so1ve** [comment]
sorry, i forgot to add them back

**Comment by so1ve** [comment]
please wait

**Comment by so1ve** [comment]
added

**Comment by halvardssm** [comment]
Thanks! Merged it now!

**Pull request merged**
